server:
  port: 8080

spring:
  application:
    name: acgagent-gateway
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: user-service
          uri: lb://acgagent-service-user
          predicates:
            - Path=/api/user/**
