spring:
  cloud:
    gateway:
      routes:
        - id: user-service
          uri: lb://acg-user
          predicates:
            - Path=/api/auth/**,/api/users/**,/api/roles/**,/api/permissions/**,/druid/**
        - id: agent-service
          uri: lb://acg-chat
          predicates:
            - Path=/api/agents/**,/api/chat/**,/api/prompts/**